name: RainbowChat
version: ${project.version}
main: com.github.beelzebu.rainbowchat.RainbowChat
api-version: 1.16
authors: [ Beelzebu ]
description: JSON chat with rgb support for 1.16+
depend:
- CommandLib
softdepend: [ PlaceholderAPI, Towny ]
